### ISSUE TITLE
Readme is misleading

### ISSUE THREAD

**Issue by OmgImAlexis** [beameio/beame-insta-ssl#1]
You can use ngrok with let's encrypt which means you don't need to pay for a SSL cert as let's encrypt certs are 100% free. The readme should be changed to reflect this.

**Comment by sophiabeame** [comment]
Thanks for your feedback, you make a valid point. I will add that to our readme. It's true that you can use let's encrypt with ngrok, without paying for a cert, but you still have to pay ngrok and configure DNS (and with insta-ssl it works out of the box, with one command). I hope you will take it for a spin! Happy to answer any further questions.
