### ISSUE TITLE
Expired certificate

### ISSUE THREAD

**Issue by Mbugus2008** [beameio/beame-insta-ssl#11]
My Certificate has expired, how do i get another one.

**Comment by zglozman** [comment]
wierd they are supposed to be six months, please check the clock on your computer.

**Comment by zglozman** [comment]
please send us your beame fqdn and will check on our end.

**Comment by portwaypoint** [comment]
I got this message when I tried to run the 'create' command again. Perhaps this is where the confusion lies? The certificate is still valid nevertheless.

$ beame-insta-ssl create 'BIG_TOKEN_FROM_EMAIL'

[2017-01-10 16:03:54] [BeameStore] INFO: Registering credential https://someaddress.v1.p.beameio.net ...
ERROR { message: 'authToken.signedData.valid_till is in the past - token expired',
  module: 'ProvisionApi',
  data: 
   { status: 401,
     message: 'authToken.signedData.valid_till is in the past - token expired',
     url: 'https://someaddress.something.somewhere/node/auth/register',
     postData: 
      { name: 'My name',
        email: 'something',
        parent_fqdn: undefined,
        edge_fqdn: 'stuff' } },
  code: 'ApiRestError' }

**Comment by sophiabeame** [comment]
The certificates should be valid, but the tokens do expire after 2 days for security purposes. If your token expired, you can let me know your email by emailing me at sophia@beame.io and I will remove your registration which will allow you to re-register and get a new token! All the best!
