### ISSUE TITLE
'Unexpected token =' error on 'beame-insta-ssl create'

### ISSUE THREAD

**Issue by briangonzalezmia** [beameio/beame-insta-ssl#14]
I ran the 'beame-insta-ssl create' command exactly as sent by email and received the following error. Any help is appreciated.

'/usr/local/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/ProxyClient.js:155
	createLocalServerConnection(data, callback = nop) {
	                                           ^

SyntaxError: Unexpected token =
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/beame-insta-ssl/node_modules/beame-sdk/src/services/BeameServer.js:8:21)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)'

**Comment by zglozman** [comment]
Turns out we had an issue pls retry

**Comment by zglozman** [comment]
Sorry this is again this Ecma script you need to update your node to 6.9

**Comment by briangonzalezmia** [comment]
Updated node as requested now shows the following

'[2017-01-03 07:58:14] [BeameStore] INFO: Registering credential https://ypxf72akb6onjvrq.ohkv8odznwh5jpwm.v1.p.beameio.net ...
ERROR { message: 'authToken.signedData.valid_till is in the past - token expired',
  module: 'ProvisionApi',
  data: 
   { status: 401,
     message: 'authToken.signedData.valid_till is in the past - token expired',
     url: 'https://ypxf72akb6onjvrq.ohkv8odznwh5jpwm.v1.p.beameio.net/node/auth/register',
     postData: 
      { name: 'Brian Gonzalez',
        email: 'briangonzalezmia@gmail.com',
        parent_fqdn: undefined,
        edge_fqdn: 'xb5fbpf258kpvl3v.tr9k0gta5imrufpf.v1.p.beameio.net' } },
  code: 'ApiRestError' }
'

**Comment by zglozman** [comment]
U need to register again and get a different token

**Comment by zglozman** [comment]
Did it work out ?

**Comment by briangonzalezmia** [comment]
Like a charm… using mamp on computer -> assigned a dyn hostname locally -> set dyn address as beame hostname. Now all assets work.

**Comment by zglozman** [comment]
What did u donwith dyn its a new one for us ?

**Comment by briangonzalezmia** [comment]
I use Dyn address as hostname in MAMP and typically had to open ports on router for access. I mapped dyn to beame —hostname and closed the ports on router and now I have a perfect tunnel that terminates using my dyn hostname.
