### ISSUE TITLE
error during creating

### ISSUE THREAD

**Issue by shrisha108** [beameio/beame-insta-ssl#18]
Hello,
Can't figure it out what I'm doing wrong. Everything (openssl, node, npm) looks like installed properly. 

Here is a log:

c:\>beame-insta-ssl create 'code from beame insta'
[2017-01-29 21:47:37] [BeameStore] INFO: Registering credential https://ypxf72akb6onjvrq.ohkv8odznwh5jpwm.v1.p.beameio.net ...
[2017-01-29 21:47:38] [BeameStore] INFO: Credential aydqd7njmlwog42b.v1.p.beameio.net registered successfully ...
[2017-01-29 21:47:38] [BeameStore] INFO: Credential retrieving auth server creds of ypxf72akb6onjvrq.ohkv8odznwh5jpwm.v1.p.beameio.net...
[2017-01-29 21:47:40] [BeameStore] INFO: Signature signed by ypxf72akb6onjvrq.ohkv8odznwh5jpwm.v1.p.beameio.net verified successfully
[2017-01-29 21:47:40] [BeameStore] INFO: Credential auth server creds received for ypxf72akb6onjvrq.ohkv8odznwh5jpwm.v1.p.beameio.net ...
[2017-01-29 21:47:40] [BeameStore] INFO: Credential generating CSR on aydqd7njmlwog42b.v1.p.beameio.net...
(node:5760) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:5760) DeprecationWarning: Calling an asynchronous function without callback is deprecated.
[2017-01-29 21:47:43] [BeameStore] ERROR: Failed to generate CSR
ERROR { message: 'Failed to generate CSR',
  module: 'OpenSSL',
  data:
   { error:
      { Error: Command failed: openssl req -key C:\Users\Shrisha Das\.beame\v2\aydqd7njmlwog42b.v1.p.beameio.net\private_key.pem -new -subj "/C=US/ST=Florida/L=Gainesville/O=LFE.COM, Inc/OU=Development/CN=aydqd7njmlwog42b.v1.p.beameio.net"
      unknown option Das\.beame\v2\aydqd7njmlwog42b.v1.p.beameio.net\private_key.pem
      req [options] <infile >outfile
      where options  are
       -inform arg    input format - DER or PEM
       -outform arg   output format - DER or PEM
       -in arg        input file
       -out arg       output file
       -text          text form of request
       -pubkey        output public key
       -noout         do not output REQ
       -verify        verify signature on REQ
       -modulus       RSA modulus
       -nodes         don't encrypt the output key
       -engine e      use engine e, possibly a hardware device
       -subject       output the request's subject
       -passin        private key password source
       -key file      use the private key contained in file
       -keyform arg   key file format
       -keyout arg    file to send the key to
       -rand file;file;...
                      load the file (or the files in the directory) into
                      the random number generator
       -newkey rsa:bits generate a new RSA key of 'bits' in size
       -newkey dsa:file generate a new DSA key, parameters taken from CA in 'file'
       -newkey ec:file generate a new EC key, parameters taken from CA in 'file'
       -[digest]      Digest to sign with (md5, sha1, md2, mdc2, md4)
       -config file   request template file.
       -subj arg      set or modify request subject
       -multivalue-rdn enable support for multivalued RDNs
       -new           new request.
       -batch         do not ask anything during request generation
       -x509          output a x509 structure instead of a cert. req.
       -days          number of days a certificate generated by -x509 is valid for.
       -set_serial    serial number to use for a certificate generated by -x509.
       -newhdr        output "NEW" in the header lines
       -asn1-kludge   Output the 'request' in a format that is wrong but some CA's
                      have been reported as requiring
       -extensions .. specify certificate extension section (override value in config file)
       -reqexts ..    specify request extension section (override value in config file)
       -utf8          input characters are UTF8 (default ASCII)
       -nameopt arg    - various certificate name options
       -reqopt arg    - various request text options

          at ChildProcess.exithandler (child_process.js:211:12)
          at emitTwo (events.js:106:13)
          at ChildProcess.emit (events.js:191:7)
          at maybeClose (internal/child_process.js:885:16)
          at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
        killed: false,
        code: 1,
        signal: null,
        cmd: 'openssl req -key C:\\Users\\Shrisha Das\\.beame\\v2\\aydqd7njmlwog42b.v1.p.beameio.net\\private_key.pem -new -subj "/C=US/ST=Florida/L=Gainesville/O=LFE.COM, Inc/OU=Development/CN=aydqd7njmlwog42b.v1.p.beameio.net"' },
     stderr: 'unknown option Das\\.beame\\v2\\aydqd7njmlwog42b.v1.p.beameio.net\\private_key.pem\r\nreq [options] <infile >outfile\r\nwhere options  are\r\n -inform arg    input format - DER or PEM\r\n -outform arg   output format - DER or PEM\r\n -in arg        input file\r\n -out arg       output file\r\n -text          text form of request\r\n -pubkey        output public key\r\n -noout         do not output REQ\r\n -verify        verify signature on REQ\r\n -modulus       RSA modulus\r\n -nodes         don\'t encrypt the output key\r\n -engine e      use engine e, possibly a hardware device\r\n -subject       output the request\'s subject\r\n -passin        private key password source\r\n -key file      use the private key contained in file\r\n -keyform arg   key file format\r\n -keyout arg    file to send the key to\r\n -rand file;file;...\r\n                load the file (or the files in the directory) into\r\n                the random number generator\r\n -newkey rsa:bits generate a new RSA key of \'bits\' in size\r\n -newkey dsa:file generate a new DSA key, parameters taken from CA in \'file\'\r\n -newkey ec:file generate a new EC key, parameters taken from CA in \'file\'\r\n -[digest]      Digest to sign with (md5, sha1, md2, mdc2, md4)\r\n -config file   request template file.\r\n -subj arg      set or modify request subject\r\n -multivalue-rdn enable support for multivalued RDNs\r\n -new           new request.\r\n -batch         do not ask anything during request generation\r\n -x509          output a x509 structure instead of a cert. req.\r\n -days          number of days a certificate generated by -x509 is valid for.\r\n -set_serial    serial number to use for a certificate generated by -x509.\r\n -newhdr        output "NEW" in the header lines\r\n -asn1-kludge   Output the \'request\' in a format that is wrong but some CA\'s\r\n                have been reported as requiring\r\n -extensions .. specify certificate extension section (override value in config file)\r\n -reqexts ..    specify request extension section (override value in config file)\r\n -utf8          input characters are UTF8 (default ASCII)\r\n -nameopt arg    - various certificate name options\r\n -reqopt arg    - various request text options\r\n\r\n' },
  code: 'OpenSSLError' }

c:\>

Thank you.

**Comment by AlexzxelA** [comment]
Hi,
You have a space in home dir path. This made it fail. We will fix the scenario and inform you.

**Comment by shrisha108** [comment]
I thought so, good, will wait for fix. thank you.

**Comment by shrisha108** [comment]
Is it fixed? Can I close this issue?

**Comment by ilyash** [comment]
I have just tested get and renew certificate operations on Windows with username that includes space. The issue is fixed.
