### ISSUE TITLE
Multiple beame's

### ISSUE THREAD

**Issue by mmphego** [beameio/beame-insta-ssl#20]
Hi 
Can I have multiple beame-insta -ssl running at the same time with different ports?
eg beame-insta-ssl tunnel 1880 http and beame-insta-ssl tunnel 5050 http, simultaneously without conflict?

**Comment by zglozman** [comment]
u need to have multiple certs for that. to do that use the following command

git clone https://github.com/beameio/beame-sdk.git
cd beame-sdk 
node ./src/cli/beame.js creds getCreds --fqdn YOUR-EXSITING-FQDN 

You can generate up to 50 of them for free, let me know if it works

**Comment by mmphego** [comment]
Thanks @zglozman
