### ISSUE TITLE
Help with running on windows

### ISSUE THREAD

**Issue by kain1000000** [beameio/beame-insta-ssl#23]
Hi, and thanks for this tool. 

I'm really sure it'll be awesome... If I can get it to work. 
I've installed on Windows 10 (it took HOURS because the instructions weren't very clear, with a lot conflicting directions though), registered, and created a tunnel by running the required command. 
I see that a tunnel has been opened,  with an https link to my localhost on port 80. 

However, try as I might I can't seem to connect to the link. I get a 'page does not exist' error. 

I've also tried ngrok, but the difference is the link does 'link' me to my server page. 

I don't know what's wrong. I'm running an XAMPP server, if that helps. 

I would really appreciate your help urgently.

**Comment by ilyash** [comment]
> instructions weren't very clear

We'd like to hear which parts specifically so we could fix it.

> I get a 'page does not exist' error.

Is it coming from your browser or your server? Assuming it comes from your _server_ (which is more probable) and you are using _terminating tunnel_, it's possible you should use `--hostname` switch ("Host:" header to set in incoming requests).

Did you check how your server responds when accessed locally using http://localhost/ ?

**Comment by kain1000000** [comment]
Below is what i see in the command window after running the command:  beame-insta-ssl tunnel 80 http


$ beame-insta-ssl tunnel 80 http
Starting tunnel https://cs1bsqtmjaxngypf.v1.p.beameio.net -> http://localhost:80

Going to https://cs1bsqtmjaxngypf.v1.p.beameio.net , on firefox, I get the following message on the page:

Server not found

Firefox can’t find the server at cs1bsqtmjaxngypf.v1.p.beameio.net.

    Check the address for typing errors such as ww.example.com instead of www.example.com
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.



However, using ngrok, the link generated opens up the server page.

**Comment by ilyash** [comment]
There is no DNS record for cs1bsqtmjaxngypf.v1.p.beameio.net . We use crypto in our requests, including the request to update DNS record for your hostname. For crypto to work the clock must be set correctly. On the server I can see that your request to update DNS record has failed because the clock on your end is in the future.

Can you please check that your clock is correct and the time zone is configured properly?

Update:
If the issue is really the clock, you'll need to register again after you fix it.

**Comment by kain1000000** [comment]
The clock is correct

**Comment by kain1000000** [comment]
the timezone settings are all correct. 
Is there any other solution?

**Comment by ilyash** [comment]
Since your request was the only one with this error and I've checked that our server is synchronized against NTP servers, let's double check your computer with the command `w32tm /stripchart /computer:pool.ntp.org`

**Comment by kain1000000** [comment]
PS C:\Users\kain1000000> w32tm /stripchart /computer:pool.ntp.org
Tracking pool.ntp.org [169.255.57.61:123].
The current time is 12-Feb-17 1:11:11 PM.
13:11:11, d:+00.0883589s o:-00.0101292s  [                           *                           ]
13:11:13, d:+00.2113198s o:+00.0136557s  [                           *                           ]
13:11:15, d:+00.1387007s o:+00.0468419s  [                           *                           ]
13:11:18, d:+00.2361425s o:+00.0026544s  [                           *                           ]
13:11:20, d:+00.0508453s o:+00.0137546s  [                           *                           ]

**Comment by kain1000000** [comment]
PS C:\Users\kain1000000> w32tm /stripchart /computer:pool.ntp.org
Tracking pool.ntp.org [169.255.57.61:123].
The current time is 12-Feb-17 1:11:11 PM.
13:11:11, d:+00.0883589s o:-00.0101292s  [                           *                           ]
13:11:13, d:+00.2113198s o:+00.0136557s  [                           *                           ]
13:11:15, d:+00.1387007s o:+00.0468419s  [                           *                           ]
13:11:18, d:+00.2361425s o:+00.0026544s  [                           *                           ]
13:11:20, d:+00.0508453s o:+00.0137546s  [                           *                           ]
13:11:22, d:+00.0452847s o:+00.0088399s  [                           *                           ]
13:11:34, d:+00.0626325s o:+00.0072818s  [                           *                           ]
13:11:36, d:+00.0550758s o:+00.0151330s  [                           *                           ]
13:11:38, d:+00.1737729s o:+00.0470559s  [                           *                           ]
13:11:40, d:+00.2355506s o:+00.0147125s  [                           *                           ]
13:11:43, d:+00.2366588s o:+00.0029162s  [                           *                           ]
13:11:45, d:+00.0564187s o:+00.0126139s  [                           *                           ]
13:11:47, d:+00.0671337s o:+00.0198007s  [                           *                           ]
13:11:49, d:+00.0475838s o:+00.0071944s  [                           *                           ]
13:11:51, d:+00.0983408s o:+00.0322101s  [                           *                           ]
13:11:53, d:+00.4185404s o:+00.0512930s  [                           *                           ]
13:11:56, d:+00.2864810s o:+00.1237538s  [                           *                           ]
13:11:58, d:+00.1889022s o:-00.0084661s  [                           *                           ]
13:12:00, d:+00.2383064s o:+00.0334961s  [                           *                           ]
13:12:02, d:+00.2368058s o:+00.0295100s  [                           *                           ]
13:12:05, d:+00.2365465s o:-00.0029023s  [                           *                           ]
13:12:07, d:+00.1336680s o:+00.0457295s  [                           *                           ]
13:12:09, d:+00.2373224s o:+00.0040323s  [                           *                           ]
13:12:11, d:+00.3423344s o:+00.1208182s  [                           *                           ]
13:12:14, d:+00.0501227s o:+00.0108884s  [                           *                           ]
13:12:16, d:+00.0631732s o:+00.0178929s  [                           *                           ]
13:12:18, d:+00.0497764s o:+00.0064888s  [                           *                           ]
13:12:20, d:+00.2746627s o:+00.0381747s  [                           *                           ]
13:12:22, error: 0x800705B4
13:12:25, d:+00.2082610s o:-00.0573020s  [                           *                           ]
13:12:27, d:+00.4420457s o:+00.1725835s  [                           *                           ]
13:12:30, error: 0x800705B4
13:12:34, error: 0x800705B4

**Comment by ilyash** [comment]
I assume that either our server or your computer were out of sync at the time of registration. Can you try to re-register please (using different email address, such as your_email+beame01@example.com ) ?

**Comment by kain1000000** [comment]
ok. I'll reregister

**Comment by kain1000000** [comment]
PS C:\Users\kain1000000> beame-insta-ssl tunnel 80 http
tunnel requires --fqdn parameter because you have more than one certificate
Possible FQDNs are:
  cfkvikeccxl6tgoe.v1.p.beameio.net
  cs1bsqtmjaxngypf.v1.p.beameio.net

**Comment by ilyash** [comment]
Use `--fqdn  cfkvikeccxl6tgoe.v1.p.beameio.net` , that's the new one

**Comment by kain1000000** [comment]
ok. thanks. let me try that now

**Comment by kain1000000** [comment]
IT WORKS!!!!!! Thank you sooooo so much!!!!!!!

**Comment by ilyash** [comment]
Glad to hear it works for you!
