### ISSUE TITLE
Tunnel error - edge server address missing

### ISSUE THREAD

**Issue by AmrMorgan** [beameio/beame-insta-ssl#28]
i would first thank you all for this amazing effort
i get this error while creating tunnel
`Tunnel error: Error: FQDN xxxxxxxxxxxxxxxxx.beameio.net can not be used for tunnel - edge server address missing`
i followed the instructions in the docs to install the certificates yet this error is showing up

**Comment by mlengse** [comment]
hi, is this solved?
i got same error

**Comment by zglozman** [comment]
yes should be

**Comment by AmrMorgan** [comment]
would you give more details , Thanks
