### ISSUE TITLE
Works behind proxy?

### ISSUE THREAD

**Issue by guillermonoainquantion** [beameio/beame-insta-ssl#33]
I have a setup where nginx is running in a Docker container listening to port 80. Ngrok seems to work fine, but I cant make beame-insta-ssl to work. I think it might be because of my corporate proxy, but I don't much about this kind of networking.

I use the following command
```
beame-insta-ssl tunnel make --dst 80 --proto http
```

And I get the following output
```
Starting tunnel https://nyib4zdzykmx6396.v1.p.beameio.net -> http://localhost:80
```

Unfortunately, when accessing the URL I get the following in the browser (Chrome)
```
This site can’t be reached
nyib4zdzykmx6396.v1.p.beameio.net unexpectedly closed the connection.
```

**Comment by zglozman** [comment]
Are you going there via https or http ? It needs to be https

**Comment by guillermonoainquantion** [comment]
Well, here is where my vast ssl knowledge shines: what should explicitly go through https? The nginx server is listening in port 80, so there is no ssl involved in that end. Does it means I have to enable ssl in the server? That I have to install the beame certificate in the server? I am so knowledgeable :(

**Comment by guillermonoainquantion** [comment]
I just confirmed that it is an issue with the corporate authenticated proxy. Is there something that can be done?

**Comment by zglozman** [comment]
So you mean the beame-insta-ssl client does not connect to our cloud router  or between the beame-insta-ssl and ngix

**Comment by guillermonoainquantion** [comment]
I think it is between beame-insta-ssl and nginx. In my corporate network, behind the proxy, I'm not able to make it work, but I can through a public network, so I guess it has to do with that.

**Comment by ilyash** [comment]
I see in logs that you managed to have some traffic through the tunnel so it should not be "This site can’t be reached" error anymore. Which error(s) did you observe? (We can't see it on our tunneling server because the traffic is encrypted)

**Comment by guillermonoainquantion** [comment]
I am pretty sure that traffic was generated when using a public network. As soon as I connect to the proxied network, all I get is the unexpected close of the connection.

**Comment by ilyash** [comment]
Sorry for the delay. Still relevant?

**Comment by guillermonoainquantion** [comment]
I ended up giving up on this as it's probably a fault on my side of the network, so I'd say this is not relevant anymore. Thanks for the help!

**Comment by ilyash** [comment]
OK. If you'd like to continue at any point, please gather as much info as you can about your network layout and re-open this issue.
