### ISSUE TITLE
file 'ms\ntdll.mak' not found

### ISSUE THREAD

**Issue by Mbugus2008** [beameio/beame-insta-ssl#35]
C:\OpenSSL-Win64>nmake -f ms\ntdll.mak

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

NMAKE : fatal error U1052: file 'ms\ntdll.mak' not found
Stop.

**Comment by ilyash** [comment]
Please make sure you followed Windows build instructions carefully, looks like you missed a step (or more).

Reopen if needed.
