### ISSUE TITLE
TCP tunnels support

### ISSUE THREAD

**Issue by jbaron-mx** [beameio/beame-insta-ssl#39]
Does beame-insta-ssl support tcp tunnels? Like to expose 22 ssh port

**Comment by zglozman** [comment]
Yes pls cosult advanced section of readme

**Comment by jbaron-mx** [comment]
Whoops, sorry 😅 I've missed that from the readme. Close.

**Comment by zglozman** [comment]
We need to package it nicer. But it works great use it every day. Checkout
the gatekeepe a really new concept

**Comment by jbaron-mx** [comment]
Thanks, I'll take a look at it probably this weekend that I have some free time. Keep up the good work! 💪🏻
