### ISSUE TITLE
Tunnel Issue

### ISSUE THREAD

**Issue by kabinud** [beameio/beame-insta-ssl#4]
When I run "beame-insta-ssl tunnel 8008 http" I get the following....

(node:80118) DeprecationWarning: BeameStoreV2#getCredential is deprecated. Use BeameStoreV2#find instead. Use --trace-deprecation NodeJS flag for trace.

then when i try to access the tunnel url provided I get

/usr/local/lib/node_modules/beame-insta-ssl/node_modules/http-proxy/lib/http-proxy/index.js:119
    throw err;
    ^

Error: connect ECONNREFUSED 127.0.0.1:8081
    at Object.exports._errnoException (util.js:1007:11)
    at exports._exceptionWithHostPort (util.js:1030:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1080:14)

**Comment by ilyash** [comment]
Do you see the `Starting tunnel ...` message? If yes, which ports does it mention? I have something like `Starting tunnel https://something-long-here.beameio.net -> http://localhost:8008`.

It seems very strange that the given port and the port that is actually used do not match. Can you please double check?

Please tell us your OS name and version and NodeJS version.

**Comment by stephan1827** [comment]
I had the same issue with the error. It seems to be triggered when nothing on the port is there to answer the request.

Stephan

**Comment by kabinud** [comment]
It seems you are correct I created a sample node server (see below) and it worked.  Perhaps in readme file there needs to be a sample such as this for others to have a sample or perhaps have a more appropriate error showing when nothing is available at given port

var express = require('express');
var app = express();

app.get('/', function (req, res) {
  res.send('Hello World!'); // This will serve your request to '/'.
});

app.listen(8008, function () {
  console.log('Example app listening on port 8008!');
 });

**Comment by stephan1827** [comment]
Hi,
that would be great. I use your service to run a local skill for Amazons Alexa. It works great but of course during development a lot of times my app crashes. If that happens and Alexa trys to run the local skill your app crashed too. It would be great if it just shows an error and keeps on running until the service behind the port is back up.

Stephan

**Comment by zglozman** [comment]
How exactly are u making it crash ? If it crashes it's a bug, which we will fix.  I Am developing a video streaming and using it edlxcaty that way

**Comment by stephan1827** [comment]
It is actually quite easy. I start the app on my Mac and paste the URL in my browser without starting the web service. That makes is throw the error and crash. I will try to send you a PM with a short video. Let me know if there is anything I can do to help.

**Comment by ilyash** [comment]
We have changed the behaviour to something more reasonable.

```
$ beame-insta-ssl tunnel 127.0.0.1:65000 http --fqdn whatever-here.beameio.net
Starting tunnel https://whatever-here.beameio.net -> http://127.0.0.1:65000
Error connecting to 127.0.0.1:65000 - Error: connect ECONNREFUSED 127.0.0.1:65000
```

... and the server keeps running

**Comment by ilyash** [comment]
Please make sure you update to version 0.0.7 to get the new behaviour

**Comment by stephan1827** [comment]
Works great now, thanks for the quick fix. Final suggestion for the installation process I have to run

npm install -g beame-insta-ssl 

with sudo on a Mac otherwise I get permission issues. Most people will figure this
out on their own but it can’t hurt to mention it in the documentation.

Stephan
