### ISSUE TITLE
how to reset account?

### ISSUE THREAD

**Issue by linuxfreakus** [beameio/beame-insta-ssl#44]
I failed to save the dotfile directory that was created, and I am not sure there is a way to reset my account now using a new cert.  I don't want to use a different email address.

**Comment by ilyash** [comment]
A simple trick is to use an email address that will be unique for our system but will actually be the same one that you are using. For example for your.email@example.com you can use your.email+01@example.com . The emails you will receive to your.email+01@example.com will go into your.email@example.com inbox.

**Comment by linuxfreakus** [comment]
I'm aware of that, but it still creates hassles and another thing to keep
track of.  I ended up writing my own anyway and just running it in a cheap
AWS ECS container, then I can have non-terminating SSL and for a single
person I have full control, or I could even share it with people if I
wanted.  Not as many features as beame for sure since I just whipped it
together, but for now, I'll take the tradeoff.

**Comment by zglozman** [comment]
can you provision publicly trusted certs?

**Comment by linuxfreakus** [comment]
Yes, as long as I'm already using AWS for other stuff anyway, it doesn't
cost me extra to use their certificate manager to generate as many certs as
I want.  They only work on an ALB or ELB or CloudFront, but for personal
use its fine, it doesn't need to be scalable to multiple nodes which would
take more work to figure out how since ALB/ELB don't have a lot of
capabilities compared to HAProxy for example.
