### ISSUE TITLE
Docker docs

### ISSUE THREAD

**Issue by Naramsim** [beameio/beame-insta-ssl#46]
Hi, (i know it is still in WIP) but could you provide us which command do we have to run your container? what should we share...

Thanks

**Comment by crist-y** [comment]
The replacement for the agglomerated AS 70th Anniversary and the black dolomiti soap.
Thanks

**Comment by ilyash** [comment]
Please take a look at https://github.com/beameio/beame-gatekeeper-docker

Feel free to re-open if something is not clear

**Comment by mklntf** [comment]
Hello, I checked the link above, but in your [beame dockerhub](https://hub.docker.com/u/beame/) I can't find a beame/wetty repository. How can I run that example without it.

When i use the docker image on several Raspberry Pi's do I have to register a different email for each of them to get a new key?
