### ISSUE TITLE
ERROR: Host Registration Error Invalid Payload Signature

### ISSUE THREAD

**Issue by acecombat2** [beameio/beame-insta-ssl#55]
![beame](https://user-images.githubusercontent.com/31785435/35763089-352c7566-08df-11e8-9d8d-bc2b12d5b3d5.PNG)

Greetings,

How do I solve the error?

 I'm copied from my old Windows 7 OS to another Newly Installed Windows 10 OS via copying the .beame folder.

I did renew the cert without issues and setDns --useBestProxy and it still came with the same error.

**Comment by zglozman** [comment]
It either has to do with the time, or version of openssl

**Comment by acecombat2** [comment]
@zglozman what do you meant by 'time'? is it the machine's date and time settings? And the openssl's version installed is 'OpenSSL 1.0.2l 25 May 2017' I downloaded it from Light Production.

**Comment by acecombat2** [comment]
Settled the issue by updating NPM from 5.6.0 to latest 9.9.X
