### ISSUE TITLE
[ProxyClient] ERROR: Host registration error Invalid payload signature

### ISSUE THREAD

**Issue by dok18** [beameio/beame-insta-ssl#57]
Hi,

I am receiving this error since yesterday 

```
pi@rpi:~ $ beame-insta-ssl tunnel make --dst 127.0.0.1:80 --proto http
Starting tunnel https://xxxxxxxxxxxxx.v1.p.beameio.net -> http://127.0.0.1:80
(node:10178) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:10178) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:10178) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:10178) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
Proxy client started on xxxxxxxxxxxxx.v1.p.beameio.net
[2018-04-18 13:43:46] [ProxyClient] ERROR: Host registration error Invalid payload signature
```

Any ideas?

**Comment by zglozman** [comment]
expired cert maybe ?

________________________________

**Comment by dok18** [comment]
Not expired. But my local clock was 8 hours behind correct time.

**Comment by bockholt** [comment]
What is the correct time? UTC time zone? You changed the host date/time? Facing the same problem here...

**Comment by zglozman** [comment]
Correct time is the correct time. (-: u should use NTP to make sure. Your computer clock gets setup in UTC, the os converts it to ur timezone

**Comment by bockholt** [comment]
ok, got it. Runned the following, just in case:

sudo ntpdate -qu 1.ro.pool.ntp.org
server 194.102.58.173, stratum 2, offset -0.009673, delay 0.22665
server 85.204.240.2, stratum 2, offset -0.010339, delay 0.21817
server 89.36.93.8, stratum 2, offset -0.013715, delay 0.22972
server 93.190.144.19, stratum 2, offset -0.007237, delay 0.23000
20 Dec 17:43:02 ntpdate[2902]: adjust time server 85.204.240.2 **offset -0.010339 sec**

then runned: 
beame-insta-ssl tunnel make --dst 5006 --proto http --fqdn <my_id>.v1.p.beameio.net

and got the same Error: **[ProxyClient] ERROR: Host registration error Invalid payload signature**
**fqdn     │ parent                                                                                  │ valid                               │ priv/k**
<my_id> │ ypxf72akb6onjvrq.ohkv8odznwh5jpwm.v1.p.beameio.net  │ 2019-11-26 13:08:01     │ Y

Any ideas on how to tunnel again on using <my_id> ?
