### ISSUE TITLE
wrap inside of the package

### ISSUE THREAD

**Issue by jjhesk** [beameio/beame-insta-ssl#58]
can i do so because i am trying to wrap the module inside the package for standalone ship.

for the beame-sdk, how does it work out of the sdk?

**Comment by organom** [comment]
Hi @jjhesk ,

Insta-ssl wraps the beame-sdk and most of the underlining functionality happens at the beame-sdk level. 

If your idea is to wrap the insta-ssl for offline installation, npm allows it via the [bundleddependencies](http://npm.github.io/using-pkgs-docs/package-json/types/bundleddependencies.html).
An easy way to pack all the dependencies is by installing [bundle-deps](https://www.npmjs.com/package/bundle-deps):
```
npm install -g bundle-deps
bundle-deps
npm pack
```
then the result `beame-insta-ssl-1.*.tgz` will contain all that it needs.
to install from it using `npm install beame-insta-ssl-1.*.tgz`


Please reopen or create a new issue if extra help is still required
