### ISSUE TITLE
[ProvisionApi] ERROR: API POST on https://<address>:: Access Denied

### ISSUE THREAD

**Issue by mklntf** [beameio/beame-insta-ssl#63]
Hello,

my beame-insta-ssl doesn't work anymore. I tried to set new DNS but i get always an error message. 
```
beame-insta-ssl creds setDns --fqdn <fqdn> --useBestProxy true
OUTPUT: [ProvisionApi] ERROR: API POST on https://<address>:: Access Denied
```
When I start a tunnel it seems like everything is fine, but it's not.
```
beame-insta-ssl tunnel make --dst 3000 --proto http
Proxy client started on <fqdn>
```

How to resolve this?

**Comment by zglozman** [comment]
most likley ur computer clock is off

________________________________

**Comment by mklntf** [comment]
It runs on a Raspberry Pi, Clock seems fine, Timezone is Vienna, Austria. How could the clock affect if beame-insta-ssl is running or not?

I might have changed the timezone, so it might differ from the timezone when I installed beame-insta-ssl.

I also stored the .beame folder and restored it after a complete new installation on the raspberry.
