### ISSUE TITLE
Tunnel not starting

### ISSUE THREAD

**Issue by gdrimes** [beameio/beame-insta-ssl#65]
I have beame-insta-ssl working on a Windows 10 machine but I get an error on my Windows 7 machine.

When I do the following command in PowerShell:
**beame-insta-ssl tunnel make --dst 8000 --proto 8000**
I get 
Starting tunnel https://dgce5ksys4671xhh.v1.p.beameio.net -> http://localhost:8000
(node:28084) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:28084) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:28084) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
(node:28084) [DEP0013] DeprecationWarning: Calling an asynchronous function without callback is deprecated.
**[2018-09-14 14:56:58] [BeameStore] ERROR: dgce5ksys4671xhh.v1.p.beameio.net null**
[2018-09-14 14:56:58] [ProxyClient] ERROR: Get dns error for dgce5ksys4671xhh.v1.p.beameio.net Unexpected error. SERVER NOT STARTED
(node:28084) UnhandledPromiseRejectionWarning: Error: Error starting HTTPS terminating proxy: defined
    at proxyClient.start.then.catch.e (C:\Users\Garry\AppData\Roaming\npm\node_modules\beame-insta-ssl\lib\tunnel.js:108:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
(node:28084) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing ins
ide of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejectio
n id: 1)
(node:28084) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejection
s that are not handled will terminate the Node.js process with a non-zero exit code.

**I suspect that the starting error is the line:**

[2018-09-14 14:56:58] [BeameStore] ERROR: dgce5ksys4671xhh.v1.p.beameio.net null

Any idea on how to fix this?

Thanks,

Garry

**Comment by ilyash-b** [comment]
Reopen if still relevant
