### ISSUE TITLE
No FreeBSD version available. Cannot find module './freebsd'

### ISSUE THREAD

**Issue by MatthewCroughan** [beameio/beame-insta-ssl#68]
Using freenas and the nextcloud plugin, thought I'd attempt to make a tunnel. Setup wasn't simple, as I'm unable to use any of the documented guides because of this one issue.

**Comment by ilyash-b** [comment]
Sorry. FreeBSD is not supported. The reason is limited resources on our end, we will happily accept contribution for FreeBSD support.
