### ISSUE TITLE
Node version 11.3.0 detected but beame-gatekeeper requires node version 8

### ISSUE THREAD

**Issue by ghost** [beameio/beame-insta-ssl#70]
While running `beame-gatekeeper-install` I get this output:

```
+ Running Mac OS installation
+ Using NodeJS at /usr/local/bin/node
+ Checking NodeJS version. Expecting Node 8.
+ ERROR: Node version 11.3.0 detected but beame-gatekeeper requires node version 8
```

This seems a bit silly, I really want to use Node 11.3.0 on my system.

Is this project alive, btw? I see a PR which fixes a typo from over a year ago.

**Comment by ilyash-b** [comment]
Node version 11.3.0 is not officially supported because we have not tested with that version. You can try to run beame-insta-ssl without installing to see whether it works with Node version 11.3.0. If it does, you could modify the installation to bypass the check. Re-open this issue if needed.

**Comment by ilyash-b** [comment]
Additional information: there are not plans to explicitly support non-LTS versions of Node. See https://nodejs.org/en/about/releases/
