### ISSUE TITLE
auto start with ubuntu

### ISSUE THREAD

**Issue by algarih** [beameio/beame-insta-ssl#73]
how to make this auto start with ubuntu ?

**Comment by organom** [comment]
Hi @algarih 
Sorry for the late reply.

Is this still an issue for you? 
Inside the `install` folder, there is a script called `systemd-service.sh`. You'll need to fine tune it to your needs ( check BEAME_INSTA_SSL_USER,  BEAME_INSTA_SSL_ARGV)

**Comment by ilyash-b** [comment]
Reopen if needed
