### ISSUE TITLE
can't start terminating server connection

### ISSUE THREAD

**Issue by pr01og** [beameio/beame-insta-ssl#74]
Building terminating server connection

32aa9afa-dfb0-4e82-85a4-9c6a308e4c90  => Client app connected
connect ECONNREFUSED 127.0.0.1:22  => Local app unreachable, please verify (Informing client)
Local connection < 32aa9afa-dfb0-4e82-85a4-9c6a308e4c90 > ended
32aa9afa-dfb0-4e82-85a4-9c6a308e4c90  => local app disconnected
Trying to reconnect local app
connect ECONNREFUSED 127.0.0.1:22  => Local app unreachable, please verify (Informing client)
Local connection < 32aa9afa-dfb0-4e82-85a4-9c6a308e4c90 > ended
32aa9afa-dfb0-4e82-85a4-9c6a308e4c90  => local app disconnected
Credential ohkv8odznwh5jpwm.tl5h1ipgobrdqsj6.v1.p.beameio.net was not found locally and allowRemote is false
Credential ohkv8odznwh5jpwm.tl5h1ipgobrdqsj6.v1.p.beameio.net was not found locally and allowRemote is false
TerminatingServer =>  _3Fl5FOVvq90tdoPAAAC  connected verified:  wm6hb5wlxw568ltn.qzb63j3zef54motp.v1.p.beameio.net
Building terminating server connection

1d54c2aa-aad0-4d3b-953f-2b22a0823883  => Client app connected
connect ECONNREFUSED 127.0.0.1:22  => Local app unreachable, please verify (Informing client)
Local connection < 1d54c2aa-aad0-4d3b-953f-2b22a0823883 > ended
1d54c2aa-aad0-4d3b-953f-2b22a0823883  => local app disconnected
Trying to reconnect local app
connect ECONNREFUSED 127.0.0.1:22  => Local app unreachable, please verify (Informing client)
Local connection < 1d54c2aa-aad0-4d3b-953f-2b22a0823883 > ended
1d54c2aa-aad0-4d3b-953f-2b22a0823883  => local app disconnected
Credential ohkv8odznwh5jpwm.tl5h1ipgobrdqsj6.v1.p.beameio.net was not found locally and allowRemote is false
Credential ohkv8odznwh5jpwm.tl5h1ipgobrdqsj6.v1.p.beameio.net was not found locally and allowRemote is false
TerminatingServer =>  UymgxwozniumMnHLAAAD  connected verified:  wm6hb5wlxw568ltn.qzb63j3zef54motp.v1.p.beameio.net
Building terminating server connection

**Comment by ilyash-b** [comment]
Reopen if still relevant
