### ISSUE TITLE
Can't connect to tunnel

### ISSUE THREAD

**Issue by benway** [beameio/beame-insta-ssl#76]
Hi,

I started the tunnel with
`beame-insta-ssl tunnel make --dst 3000 --proto http --fqdn phg9cpfajd2llyl6.v1.p.beameio.net
`
and I get the output:
`Starting tunnel https://phg9cpfajd2llyl6.v1.p.beameio.net -> http://localhost:3000
Proxy client started on phg9cpfajd2llyl6.v1.p.beameio.net`

I have a server running locally on my machine at port 3000.

Pointing to it via Chrome tells me "this site can't be reached", so I guess this endpoint is not accessing the tunnel?

I can `ping phg9cpfajd2llyl6.v1.p.beameio.net` without a problem.

Thanks!
Chris

**Comment by organom** [comment]
Hi @benway ,
Sorry for the late reply.  Are you still facing this issue?

Regards,
Ricardo

**Comment by ilyash-b** [comment]
Reopen if needed
