### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ghost** [beameio/beame-insta-ssl#79]
Whenever I run the beame-insta-ssl token, I recieve an error which says: 

{ Error: socket hang up
    at createHangUpError (_http_client.js:336:15)
    at TLSSocket.socketOnEnd (_http_client.js:429:23)
    at TLSSocket.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)
     [stack]: 'Error: socket hang up\n    at createHangUpError (_http_client.js:336:15)\n    at TLSSocket.socketOnEnd (_http_client.js:429:23)\n    at TLSSocket.emit (events.js:185:15)\n    at endReadableNT (_stream_readable.js:1206:12)\n    at process._tickCallback (internal/process/next_tick.js:158:19)',
     [message]: 'socket hang up',
     code: 'ECONNRESET' },
  url: 'https://ypxf72asadfsdfwefdedq.ohkv8odznwh5jpwm.v1.p.beameio.net/node/auth/register' }

**Comment by ghost** [comment]
can anyone help?

**Comment by organom** [comment]
Hi Agit-coder,

I believe this could be related to some infrastructure issues we had.
Can you please confirm if it still happens?

**Comment by adamsin12** [comment]
Thats related to my issue which was solved during the night. Try it again, this is exactly what it said me when running on debug level.

**Comment by organom** [comment]
Closing because it looks like it was infrastructure related. 
Please reopen/create new one if this still happens
