### ISSUE TITLE
some HTTPs requests receive net::ERR_CONTENT_LENGTH_MISMATCH

### ISSUE THREAD

**Issue by portwaypoint** [beameio/beame-insta-ssl#8]
The main .html file loads (200 status code from top-level request) but the CSS or the javascript resources fail with the above.

This is using chrome as the front end.

Any idea what might cause this?

This is using a terminating endpoint "http" of the style:

$ beame-insta-ssl tunnel 8080 http

**Comment by zglozman** [comment]
can you send the server example demonstrating this ? Its possible that its a bug, but unlikley.

**Comment by sophiabeame** [comment]
Hi there, can you send us a server example showing what it looks like? If it's a bug we can help you fix it. sophia@beame.io

**Comment by portwaypoint** [comment]
I tried the same server again, and now it redirects just fine. Has the internet to localhost "redirector" software that you host been updated with a fix?

**Comment by zglozman** [comment]
WE have had a lot of things fixed in the last few weeks, We are very activly developing (;
