### ISSUE TITLE
Is there any way to set custom subdomains?

### ISSUE THREAD

**Issue by scorpjke** [beameio/beame-insta-ssl#82]
Hi! I wanna say thanks in advance, your service is awesome. I have a question:
I was randomly assigned a subdomain:

qq5c51gzre3fq49k.v1.p.beameio.net

I'm guessing there is no way to set up a custom one (or is there?).
Then we can create a subdomain to that, for example I managed to create:

qiz0aq58hphf72vk.qq5c51gzre3fq49k.v1.p.beameio.net

Which turned out to be random, too. Is there any way to set up a custom subdomain on that level? For example:

chat.qq5c51gzre3fq49k.v1.p.beameio.net

 If so, what's the exact command that I should run? Thanks a lot in advance!

**Comment by organom** [comment]
Hi scorpjke,

Custom domains/subdomains are currently not allowed as they were planned as an enterprise feature. 
You can try to use a url shortener for convenience, like https://bitly.com/ or other similar service.

Regards,
Ricardo

**Comment by organom** [comment]
Closing, please reopen/create new issues if necessary. Thank you
