### ISSUE TITLE
Android app 

### ISSUE THREAD

**Issue by ingnelson** [beameio/beame-insta-ssl#83]
Hello.

how can i run this tunnel on android ?
can you create a apk ?

**Comment by organom** [comment]
Hello ingnelson, 

Currently there are no short term plans to natively support Android. 

What you could try is termux (or other terminal emulator for android), install nodejs and use npm to install beame-insta-ssl (https://www.freecodecamp.org/news/building-a-node-js-application-on-android-part-1-termux-vim-and-node-js-dfa90c28958f/). I didn't try it myself, so I can't promise it would work, but let me know if you try it and hit any issue
